spring:
  application:
    name: skypay
  jpa:
    hibernate:
      ddl-auto: update
      ejb:
        interceptor: org.hibernate.cfg.ImprovedNamingStrategy
        session_factory:
          use_native_entity_query: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: Africa/Casablanca
  datasource:
    url: jdbc:mysql://localhost:3306/skypay
    username: root
    password: tftftf
    oracleucp:
      database-name: skypay
 
      
server:
  port: 8081
 
logging:
  level:
    org:
      springframework:
        security:
          DEBUG
        web:
          DEBUG